/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Formularios;
import Clases.Conexion;
import Clases.Recuperacion;
import de.javasoft.plaf.synthetica.SyntheticaAluOxideLookAndFeel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import static javax.swing.JDialog.setDefaultLookAndFeelDecorated;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
/**
 *
 * @author Isaac
 */
public class CambiarContra extends javax.swing.JDialog {

    /**
     * Creates new form CambiarContra
     */
        private PreparedStatement SentenciaSQL; 
    public CambiarContra(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.getContentPane().setBackground(new java.awt.Color(203,203,203));
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ContraseñaA = new javax.swing.JLabel();
        txtActual = new javax.swing.JPasswordField();
        txtNueva = new javax.swing.JPasswordField();
        txtConfirmarNueva = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        CContraseñaN = new javax.swing.JLabel();
        ContraseñaN = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CAMBIAR CONTRASEÑA");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));
        jPanel1.setOpaque(false);

        ContraseñaA.setText("Contraseña actual:");

        jButton1.setBackground(new java.awt.Color(102, 204, 0));
        jButton1.setText("Cambiar Contraseña");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        CContraseñaN.setText("Confirmar contraseña nueva:");

        ContraseñaN.setText("Contraseña nueva:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ContraseñaA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ContraseñaN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CContraseñaN, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtActual)
                    .addComponent(txtNueva)
                    .addComponent(txtConfirmarNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContraseñaA)
                    .addComponent(txtActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContraseñaN)
                    .addComponent(txtNueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CContraseñaN)
                    .addComponent(txtConfirmarNueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (("".equals(txtActual.getText().trim()) || "".equals(txtNueva.getText().trim())) || "".equals(txtConfirmarNueva.getText().trim())) {
            JOptionPane.showMessageDialog(this,"No puede dejar campos vacíos", "AVISO", JOptionPane.ERROR_MESSAGE);
        }
        else if (!(txtNueva.getText().equals(txtConfirmarNueva.getText()))) {
            JOptionPane.showMessageDialog(this, "Las nuevas contraseñas no coinciden", "AVISO", JOptionPane.ERROR_MESSAGE);
            txtNueva.setText(null);
            txtConfirmarNueva.setText(null);
        }
        else if(txtNueva.getText().length()<4 || txtNueva.getText().length()>8)
        {
            JOptionPane.showMessageDialog(this, "La nueva contraseña debe de tener entre 4 y 8 caracteres","", JOptionPane.ERROR_MESSAGE);
        }
        else {
            try {
                SentenciaSQL = Conexion.mthPrepararSentenciaSQL("SELECT id_usuario FROM usuarios WHERE id_usuario = ? AND contraseña = ?");
                SentenciaSQL.setInt(1,Conexion.CodigoUsuario);
                SentenciaSQL.setString(2,Recuperacion.Encriptar(txtActual.getText()));
                ResultSet rs = Conexion.mthObtenerValor(SentenciaSQL);
                rs.last();
                if (rs.getRow() == 1) {

                    SentenciaSQL = Conexion.mthPrepararSentenciaSQL("UPDATE usuarios SET contraseña = ? WHERE id_usuario = ?");
                    SentenciaSQL.setString(1, Recuperacion.Encriptar(txtNueva.getText()));
                    SentenciaSQL.setInt(2, Conexion.CodigoUsuario);
                    Conexion.mthEjecutarOperacionCM(SentenciaSQL);
                    JOptionPane.showMessageDialog(this, "Los cambios tendrán efectos al reiniciar el sistema", "WARNING/AVISO", JOptionPane.INFORMATION_MESSAGE);
                    dispose();
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Datos Incorrectos", "WARNING/AVISO", JOptionPane.ERROR_MESSAGE);
                    txtActual.setText(null);
                }
            } catch (SQLException ex) {

            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //Codigo para ejecutar el look and feel
        try {
            UIManager.setLookAndFeel(new SyntheticaAluOxideLookAndFeel());
            setDefaultLookAndFeelDecorated(false);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Error en Look and Feel", "ERROR"+ e.getMessage(), JOptionPane.ERROR_MESSAGE);
        }
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CambiarContra dialog = new CambiarContra(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CContraseñaN;
    private javax.swing.JLabel ContraseñaA;
    private javax.swing.JLabel ContraseñaN;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtActual;
    private javax.swing.JPasswordField txtConfirmarNueva;
    private javax.swing.JPasswordField txtNueva;
    // End of variables declaration//GEN-END:variables
}
