/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Formularios;
import Clases.Recuperacion;
import Clases.Usuario;
import Clases.Validar;
import com.sun.awt.AWTUtilities;
import de.javasoft.plaf.synthetica.SyntheticaAluOxideLookAndFeel;
import java.awt.Shape;
import java.awt.event.KeyEvent;
import java.awt.geom.RoundRectangle2D;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
/**
 *
 * @author Isaac
 */
public class NuevoAlumno extends javax.swing.JDialog {

    /**
     * Creates new form NuevoMaestro
     */
    public NuevoAlumno(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
                setLocationRelativeTo(null);
                setResizable(false);
        ckbActivo.setSelected(true);
        ckbActivo.setVisible(false);
        getContentPane().setBackground(new java.awt.Color(203,203,203));
//        Shape forma = new RoundRectangle2D.Double(0,0,this.getBounds().width, this.getBounds().height,27,27);
//        AWTUtilities.setWindowShape(this, forma);
                //                //Se estable el calendario para que muestre fechas no menores a 10 años de edad.
        GregorianCalendar fechaMaxima = new GregorianCalendar((Calendar.getInstance().get(Calendar.YEAR))-9,(Calendar.getInstance().get(Calendar.MONTH))-12,(Calendar.getInstance().get(Calendar.DAY_OF_MONTH)));
        nac.setMaxSelectableDate(fechaMaxima.getTime());
////        //Se estable el calendario para que muestre fechas no mayores a 25 años de edad.
        GregorianCalendar fechaMinima = new GregorianCalendar((Calendar.getInstance().get(Calendar.YEAR))-24,(Calendar.getInstance().get(Calendar.MONTH))-12,(Calendar.getInstance().get(Calendar.DAY_OF_MONTH)));
        nac.setMinSelectableDate(fechaMinima.getTime());
        nac.setDate(fechaMaxima.getTime());
        nac.getDateEditor().setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtusuario = new javax.swing.JTextField();
        txtcontraseña = new javax.swing.JPasswordField();
        seis = new javax.swing.JLabel();
        siete = new javax.swing.JLabel();
        uno = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        ocho = new javax.swing.JLabel();
        confirmar = new javax.swing.JPasswordField();
        dos = new javax.swing.JLabel();
        tres = new javax.swing.JLabel();
        cuatro = new javax.swing.JLabel();
        cinco = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox();
        txtCorreo = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JFormattedTextField();
        ckbActivo = new javax.swing.JCheckBox();
        nac = new com.toedter.calendar.JDateChooser();
        UsuarioE1 = new javax.swing.JLabel();
        uno1 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        txtDui = new javax.swing.JTextField();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("NUEVO ESTUDIANTE");

        titulo.setBackground(new java.awt.Color(102, 102, 102));
        titulo.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        titulo.setForeground(new java.awt.Color(102, 102, 102));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Bienvenido/a ");

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        seis.setForeground(new java.awt.Color(255, 255, 255));
        seis.setText("Nombre de Usuario");

        siete.setForeground(new java.awt.Color(255, 255, 255));
        siete.setText("Contraseña");

        uno.setForeground(new java.awt.Color(255, 255, 255));
        uno.setText("Nombres");

        txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreKeyTyped(evt);
            }
        });

        btnAceptar.setBackground(new java.awt.Color(0, 0, 255));
        btnAceptar.setText("AGREGAR");
        btnAceptar.setBorder(null);
        btnAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        ocho.setForeground(new java.awt.Color(255, 255, 255));
        ocho.setText("Confirmar Contraseña");

        dos.setForeground(new java.awt.Color(255, 255, 255));
        dos.setText("NIE");

        tres.setForeground(new java.awt.Color(255, 255, 255));
        tres.setText("Tipo de Usuario");

        cuatro.setForeground(new java.awt.Color(255, 255, 255));
        cuatro.setText("Correo de Estudiante");

        cinco.setForeground(new java.awt.Color(255, 255, 255));
        cinco.setText("Teléfono de Estudiante");

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Estudiante" }));

        try {
            txtTelefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        ckbActivo.setText("Activo");

        nac.setDateFormatString("dd-MM-yyyy");

        UsuarioE1.setForeground(new java.awt.Color(255, 255, 255));
        UsuarioE1.setText("Fecha de Nacimiento");

        uno1.setForeground(new java.awt.Color(255, 255, 255));
        uno1.setText("Apellidos");

        txtApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidosKeyTyped(evt);
            }
        });

        txtDui.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDuiKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(ckbActivo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UsuarioE1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cinco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(seis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(siete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ocho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cuatro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(uno1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(uno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtcontraseña, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtusuario, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbTipo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nac, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                            .addComponent(txtApellidos, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(confirmar)
                            .addComponent(txtDui, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGap(190, 190, 190))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uno)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uno1)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsuarioE1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dos)
                    .addComponent(txtDui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tres)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuatro)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cinco)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seis)
                    .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(siete)
                    .addComponent(txtcontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ocho)
                    .addComponent(confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckbActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lbl1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl1.setText("Bienvenido/a  estudiante, por favor, llene seriamente los datos del formulario ");

        lbl2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl2.setText("para registrarse, y posteriormente, podrá ingresar al sistema.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl2, javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl1, javax.swing.GroupLayout.Alignment.CENTER))
                    .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl2)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyTyped
        char c;
        c=evt.getKeyChar();
        if(!(c<'0'||c>'9')) evt.consume();
    }//GEN-LAST:event_txtnombreKeyTyped

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        Calendar cale = GregorianCalendar.getInstance();
        GregorianCalendar hoy= new GregorianCalendar();
        if("".equals(txtnombre.getText()) || "".equals(txtDui.getText()) || cmbTipo.getSelectedIndex()<0   || ckbActivo.isSelected()==false || "".equals(txtusuario.getText()) || "".equals(txtcontraseña.getText())||nac.getDate()==null)
        {
            JOptionPane.showMessageDialog(this, "No puede dejar campos vacíos","WARNING", JOptionPane.ERROR_MESSAGE);
        }
        else if(txtusuario.getText().length()<5 || txtusuario.getText().length()>10 || txtcontraseña.getText().length()<4 || txtcontraseña.getText().length()>8)
        {
            JOptionPane.showMessageDialog(this, "El nombre de usuario debe tener entre 5 y 10 carácteres \nLa contraseña debe tener entre 4 y 8 carácteres","", JOptionPane.ERROR_MESSAGE);
        }
        else if (!Validar.CorreoElectronico(txtCorreo.getText()))
        {
            JOptionPane.showMessageDialog(this, "Formato de correo inválido. Verifiquelo.", "WARNING", JOptionPane.ERROR_MESSAGE);
            txtCorreo.setText("");
        }
        else if (!Validar.NumeroTelefono(txtTelefono.getText()))
        {
            JOptionPane.showMessageDialog(this, "Número de teléfono no válido. \nComience con 2,6 o 7", "WARNING", JOptionPane.ERROR_MESSAGE);
        }
        else if (!txtcontraseña.getText().equals(confirmar.getText()))
        {
            JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden", "WARNING", JOptionPane.ERROR_MESSAGE);
            txtcontraseña.setText(null);
            confirmar.setText(null);
        }
        else  if (JOptionPane.showConfirmDialog(null, "¿Desea realizar la operacón?" , "WARNING/AVISO", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
        {
            Usuario obj = new Usuario();
            String Fecha= new SimpleDateFormat("yyyy-MM-dd").format(nac.getDate());
            obj.setNacimiento(Fecha);
            obj.setNombres(txtnombre.getText());
            obj.setApellidos(txtApellidos.getText());
            obj.setIdentificador(txtDui.getText());
            obj.setTipo(cmbTipo.getSelectedItem().toString());
            obj.setCorreo(txtCorreo.getText());
            obj.setTelefono(txtTelefono.getText());
            obj.setEstado(ckbActivo.isSelected());
            obj.setUsuario(txtusuario.getText());
            obj.setContraseña(Recuperacion.Encriptar(txtcontraseña.getText()));
            if(obj.guardarUsuario())
            {
                JOptionPane.showMessageDialog(this, "Datos Guardados");
                this.dispose();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Error inesperado");
            }
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void txtApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidosKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidosKeyTyped

    private void txtDuiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDuiKeyTyped
        char c;
        c=evt.getKeyChar();
        if((c<'0'||c>'9')) evt.consume();
                if (txtDui.getText().length() >= 8)
        {
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
        }
    }//GEN-LAST:event_txtDuiKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //Codigo para ejecutar el look and feel
        try {
            UIManager.setLookAndFeel(new SyntheticaAluOxideLookAndFeel());
            setDefaultLookAndFeelDecorated(false);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Error en Look and Feel", "ERROR"+ e.getMessage(), JOptionPane.ERROR_MESSAGE);
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NuevoAlumno dialog = new NuevoAlumno(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel UsuarioE1;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel cinco;
    private javax.swing.JCheckBox ckbActivo;
    private javax.swing.JComboBox cmbTipo;
    private javax.swing.JPasswordField confirmar;
    private javax.swing.JLabel cuatro;
    private javax.swing.JLabel dos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private com.toedter.calendar.JDateChooser nac;
    private javax.swing.JLabel ocho;
    private javax.swing.JLabel seis;
    private javax.swing.JLabel siete;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel tres;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDui;
    private javax.swing.JFormattedTextField txtTelefono;
    private javax.swing.JPasswordField txtcontraseña;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtusuario;
    private javax.swing.JLabel uno;
    private javax.swing.JLabel uno1;
    // End of variables declaration//GEN-END:variables
}
