package Formularios;


import Clases.Scores;
import de.javasoft.plaf.synthetica.SyntheticaAluOxideLookAndFeel;
import java.awt.BorderLayout;
import java.awt.ComponentOrientation;
import java.awt.Toolkit;
import javax.swing.Box;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Laboratorio
 */
public class Principal2 extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal2() {
        initComponents();
        setSize(Toolkit.getDefaultToolkit().getScreenSize());
        fondo pnlFondo = new fondo();
        this.add(pnlFondo, BorderLayout.CENTER);
        //setDefaultCloseOperation(0); // Desactiva el boton cerrar
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        archivo = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        ciencias = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        lenguaje = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mate = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        sociales = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        cerrar = new javax.swing.JMenu();
        salir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jMenuBar1.setBorderPainted(false);
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        archivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Folder - Google Docs.png"))); // NOI18N
        archivo.setText("ARCHIVO");
        archivo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        archivo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        archivo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jMenuItem1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jMenuItem1.setText("Modificar mis Datos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        archivo.add(jMenuItem1);
        archivo.add(jSeparator2);

        jMenuItem2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jMenuItem2.setText("Darme de Baja");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        archivo.add(jMenuItem2);
        archivo.add(jSeparator1);

        jMenuItem7.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jMenuItem7.setText("Calificaciones");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        archivo.add(jMenuItem7);

        jMenuBar1.add(archivo);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Games alt.png"))); // NOI18N
        jMenu2.setText("JUGAR");
        jMenu2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jMenu2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });

        ciencias.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        ciencias.setText("Ciencias");
        ciencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cienciasActionPerformed(evt);
            }
        });
        jMenu2.add(ciencias);
        jMenu2.add(jSeparator3);

        lenguaje.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lenguaje.setText("Lenguaje");
        lenguaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lenguajeActionPerformed(evt);
            }
        });
        jMenu2.add(lenguaje);
        jMenu2.add(jSeparator4);

        mate.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        mate.setText("Matemáticas");
        mate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mateActionPerformed(evt);
            }
        });
        jMenu2.add(mate);
        jMenu2.add(jSeparator5);

        sociales.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        sociales.setText("Sociales");
        sociales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                socialesActionPerformed(evt);
            }
        });
        jMenu2.add(sociales);

        jMenuBar1.add(jMenu2);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Update.png"))); // NOI18N
        jMenu1.setText("CAMBIAR CONTRASEÑA");
        jMenu1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jMenu1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Power - Lock.png"))); // NOI18N
        cerrar.setText("CERRAR SESIÓN");
        cerrar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        cerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cerrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
        });
        jMenuBar1.add(cerrar);

        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Power - Shut Down.png"))); // NOI18N
        salir.setText("SALIR");
        salir.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        salir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        salir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
        });
        jMenuBar1.add(salir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 924, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 717, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
        if (JOptionPane.showConfirmDialog(null, "¿Desea salir de la aplicación?" , "", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_salirMouseClicked

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        if (JOptionPane.showConfirmDialog(null, "¿Desea cerrar sesión?", "", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
        {
            this.dispose();
            Clases.Conexion.Reiniciar();
    }//GEN-LAST:event_cerrarMouseClicked
    }
    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
       new CambiarContra(this,true).setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       new MiniLogin2(new javax.swing.JDialog(),true).setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        if (JOptionPane.showConfirmDialog(null, "¿Desea eliminar su cuenta?", "", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
        {
           new Eliminar(new javax.swing.JDialog(),true).setVisible(true);
    }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked

    }//GEN-LAST:event_jMenu2MouseClicked

    private void mateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mateActionPerformed
        Clases.Conexion.Materia= mate.getText();
        new Juego(this,true).setVisible(true);
    }//GEN-LAST:event_mateActionPerformed

    private void lenguajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lenguajeActionPerformed
        Clases.Conexion.Materia= lenguaje.getText();
        new Juego(this,true).setVisible(true);
    }//GEN-LAST:event_lenguajeActionPerformed

    private void socialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_socialesActionPerformed
        Clases.Conexion.Materia= sociales.getText();
        new Juego(this,true).setVisible(true);
    }//GEN-LAST:event_socialesActionPerformed

    private void cienciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cienciasActionPerformed
        Clases.Conexion.Materia= ciencias.getText();
        new Juego(this,true).setVisible(true);
    }//GEN-LAST:event_cienciasActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
       new NotasAlumno(this,true).setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //Codigo para ejecutar el look and feel
        try {
            UIManager.setLookAndFeel(new SyntheticaAluOxideLookAndFeel());
            setDefaultLookAndFeelDecorated(false);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Error en Look and Feel", "ERROR"+ e.getMessage(), JOptionPane.ERROR_MESSAGE);
        }
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu archivo;
    private javax.swing.JMenu cerrar;
    private javax.swing.JMenuItem ciencias;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JMenuItem lenguaje;
    private javax.swing.JMenuItem mate;
    private javax.swing.JMenu salir;
    private javax.swing.JMenuItem sociales;
    // End of variables declaration//GEN-END:variables
}
