/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Formularios;

import Clases.Conexion;
import Clases.Recuperacion;
import de.javasoft.plaf.synthetica.SyntheticaAluOxideLookAndFeel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Isaac
 */
public class Recuperar1 extends javax.swing.JDialog {

    /**
     * Creates new form Recuperar1
     */   private PreparedStatement SentenciaSQL;
    public Recuperar1(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
               setLocationRelativeTo(null);
        getContentPane().setBackground(new java.awt.Color(203,203,203));
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnContraseña = new javax.swing.JButton();
        txtCorreo = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        Usuario = new javax.swing.JLabel();
        Correo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("RECUPERACIÓN DE CONTRASEÑA");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));
        jPanel1.setOpaque(false);

        btnContraseña.setBackground(new java.awt.Color(51, 255, 255));
        btnContraseña.setText("Generar nueva contraseña");
        btnContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContraseñaActionPerformed(evt);
            }
        });

        Usuario.setText("Nombre de usuario:");

        Correo.setText("Confirmar correo:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Correo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(9, 9, 9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                    .addComponent(txtCorreo)
                    .addComponent(txtUsuario))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Usuario)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Correo)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnContraseña)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContraseñaActionPerformed
        //Se comprueba que los campos contengan valores.
        if ("".equals(txtUsuario.getText().trim()) || "".equals(txtCorreo.getText().trim())) {
            JOptionPane.showMessageDialog(this, "Datos Incorrectos", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtUsuario.setText(null);
            txtCorreo.setText(null);
        }
        //Se comprueba si el usuario existe.
        else {
            try {
                SentenciaSQL = Conexion.mthPrepararSentenciaSQL("SELECT id_usuario FROM usuarios WHERE nick = ? AND correo = ?");
                SentenciaSQL.setString(1,txtUsuario.getText());
                SentenciaSQL.setString(2,txtCorreo.getText());
                ResultSet rs = Conexion.mthObtenerValor(SentenciaSQL);
                rs.last();
                if (rs.getRow() == 1) {
                    int codigo_usuario = rs.getInt(1);
                    String Contraseña = mthGenerarContraseña();
                    SentenciaSQL = Conexion.mthPrepararSentenciaSQL("UPDATE usuarios SET contraseña = ? WHERE id_usuario = ?");
                    SentenciaSQL.setString(1, Recuperacion.Encriptar(Contraseña));
                    SentenciaSQL.setInt(2, codigo_usuario);
                    Conexion.mthEjecutarOperacionSM(SentenciaSQL);
                    Recuperacion.EnviarCorreo(txtCorreo.getText(), "Su contraseña es: " + Contraseña + "\n\nShoes Inventory System - SIS v1.0");
                    JOptionPane.showMessageDialog(this, "Contraseña enviada a su correo de manera exitosa", "WARNING", JOptionPane.INFORMATION_MESSAGE);
                    dispose();
                }
                else {
                    JOptionPane.showMessageDialog(this, "Datos Incorrectos", "ERROR", JOptionPane.ERROR_MESSAGE);
                    txtUsuario.setText(null);
                    txtCorreo.setText(null);
                }
            }
            catch (SQLException | NumberFormatException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_btnContraseñaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    }
        String mthGenerarContraseña()
            
            {
        String Contraseña = "";
        long milisegundos = new java.util.GregorianCalendar().getTimeInMillis();
        Random r = new Random(milisegundos);
        int i = 0;
        while (i < 20){
            char c = (char)r.nextInt(255);
            if ((c >= '0' && c <='9') || (c >='A' && c <='Z')) {
                Contraseña += c;
                i++;
            }
        }
        return Contraseña;
    
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //Codigo para ejecutar el look and feel
        try {
            UIManager.setLookAndFeel(new SyntheticaAluOxideLookAndFeel());
//           setDefaultLookAndFeelDecorated(false);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Error en Look and Feel", "ERROR"+ e.getMessage(), JOptionPane.ERROR_MESSAGE);
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Recuperar1 dialog = new Recuperar1(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Correo;
    private javax.swing.JLabel Usuario;
    private javax.swing.JButton btnContraseña;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
